spring:
  application:
    name: ${SPRING_APPLICATION_NAME:wasp-integration}

server:
  port: ${SPRING_SERVER_PORT:8080}
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1024

logging:
  level:
    ROOT: ${SPRING_LOGGING_LEVEL_ROOT:INFO}
